### ISSUE TITLE
No longer works as of WP 5.6

### ISSUE THREAD

**Issue by jakewhiteley** [joppuyo/remove-drop-cap#1]
Unfortunately, it looks like __experimentalFeatures has been removed, and this method no longer removes the dropCap.

**Comment by joppuyo** [comment]
Thanks for the heads up.

It could be that experimentalFeatures has been stabilized in 5.6. I intend to have compatibility with 5.6 if that is the case.

**Comment by joppuyo** [comment]
Looks like I had to modify the code a bit to make it work in WP 5.6, since the features are now registered globally and not per block.

If you update plugin to v1.1.0, it should work in WordPress 5.6.

**Comment by jakewhiteley** [comment]
Not stabilized unfortunately: I had a look at the Gutenberg github and the `experimentalFeatures` still exists if people use the plugin version of gutenberg, but they decided to just shortcircuit the whole thing if people aren't using the plugin.

Ended up having a go at them on the original PR because randomly removing functionality/APIs without warning and with no fallback is pretty lame for such a high profile project. At some point they will finally decide on how to implement the `theme.json` idea, but until then every update of WordPress seems to make something I don't want reappear in the block editor :/

**Comment by joppuyo** [comment]
Did you try the latest version of this plugin (v.1.10)? It uses a different approach (`block_editor_settings` PHP filter instead of `blocks.registerBlockType` JavaScript filter) which seems to work for me in WordPress 5.5 and 5.6.

But yeah, it seems like every update adds some new features to Gutenberg, and finding a way to disable them isn't exactly straightforward. I did some testing with `experimental-theme.json` too but I think it hasn't landed in the core yet so you'd need to install the unstable Gutenberg version from the plugin directory.
